const STORAGE_KEY='anastasiia-health-diary-v1',HISTORY_KEY='anastasiia-medical-history-v1';
const defaultHistory=[];
function normalizeHistory(list){return list.map((x,i)=>Array.isArray(x)?{id:`pdf-${i}`,date:x[0],type:x[1],title:x[2],description:x[3]||'',doctor:'',clinic:'',medications:'',notes:''}:x)}
let history=normalizeHistory(JSON.parse(localStorage.getItem(HISTORY_KEY)||JSON.stringify(defaultHistory)));
let entries=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');
const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
const newId=()=>globalThis.crypto?.randomUUID?.()||`local-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const save=()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(entries));window.healthCloud?.scheduleSync()};
const saveHistory=()=>{localStorage.setItem(HISTORY_KEY,JSON.stringify(history));window.healthCloud?.scheduleSync()};
const fmt=d=>new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',year:'numeric'}).format(new Date(d));
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));location.hash=id;window.scrollTo(0,0);if(id==='diary')renderEntries();if(id==='history')renderHistory();}
$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-view-link]').forEach(b=>b.onclick=()=>showView(b.dataset.viewLink));
const dialog=$('#entryDialog'),form=$('#entryForm');
function openEntry(item){form.reset();form.elements.id.value='';form.elements.date.value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);if(item)Object.entries(item).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v});updatePain();dialog.showModal();}
$$('[data-new-entry]').forEach(b=>b.onclick=()=>openEntry());$$('[data-close]').forEach(b=>b.onclick=()=>dialog.close());
function updatePain(){const v=+form.elements.pain.value;$('#painOut').textContent=v+(v===0?' — нет боли':v<4?' — слабая':v<7?' — умеренная':' — сильная')};form.elements.pain.oninput=updatePain;
function saveEntry(){try{const item=Object.fromEntries(new FormData(form));item.date=item.date||new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);item.pain=Number(item.pain)||0;item.id=item.id||newId();const i=entries.findIndex(x=>x.id===item.id);i<0?entries.push(item):entries[i]=item;entries.sort((a,b)=>new Date(b.date)-new Date(a.date));save();dialog.close();renderAll();showView('diary')}catch(error){alert('Не удалось сохранить запись: '+error.message)}}
form.onsubmit=e=>{e.preventDefault();saveEntry()};$('#saveEntryButton').onclick=e=>{e.preventDefault();saveEntry()};
$$('.bp-input').forEach(input=>{input.addEventListener('input',()=>{const digits=input.value.replace(/\D/g,'').slice(0,6);input.value=digits.length>3?digits.slice(0,3)+'/'+digits.slice(3):digits})});
function renderDashboard(){const last=entries[0];$('#todayDate').textContent=new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long'}).format(new Date());$('#lastPain').textContent=last?`${last.pain}/10`:'Нет записей';$('#lastPainDate').textContent=last?fmt(last.date):'—';$('#lastBp').textContent=last?(last.bpLeft||last.bpRight||'Не измерено'):'—';$('#lastMood').textContent=last?(last.wellbeing||'—'):'—';$('#recentEntries').innerHTML=entries.length?entries.slice(0,3).map(entryMini).join(''):'<div class="empty">Записей пока нет</div>';renderChart()}
function entryMini(e){return `<div class="mini-entry"><span>${fmt(e.date)}</span><div><strong>${e.wellbeing}</strong> <span class="badge">Боль ${e.pain}/10</span><br><small>${esc(e.notes||e.symptoms||'Без заметки')}</small></div><span>${esc(e.bpLeft||e.bpRight||'—')}</span></div>`}
function renderChart(){const el=$('#painChart'),days=[...entries].slice(0,14).reverse();if(!days.length){el.className='chart empty-chart';el.textContent='Пока нет данных. Добавь первую запись.';return}el.className='chart';el.innerHTML=days.map(e=>`<div class="bar-wrap" title="${fmt(e.date)}: ${e.pain}/10"><div class="bar" style="height:${e.pain*10}%"></div><small>${new Date(e.date).getDate()}</small></div>`).join('')}
function renderEntries(){const q=$('#diarySearch').value.toLowerCase(),f=$('#painFilter').value;const list=entries.filter(e=>(!q||JSON.stringify(e).toLowerCase().includes(q))&&(f==='all'||f==='0'&&e.pain===0||f==='1'&&e.pain>0||f==='7'&&e.pain>=7));$('#entriesList').innerHTML=list.length?list.map(e=>`<article class="entry-card"><div><strong>${fmt(e.date)}</strong><br><small>${new Date(e.date).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</small></div><div><h3>${esc(e.wellbeing)} · боль ${e.pain}/10</h3><div class="entry-meta"><span class="badge">АД ${esc(e.bpLeft||'—')} / ${esc(e.bpRight||'—')}</span><span class="badge">${esc(e.weather)}</span><span class="badge">${esc(e.mood)}</span><span class="badge">сон ${esc(e.sleep||'—')} ч</span><span class="badge">цикл: ${esc(e.cycle)}</span></div><p>${esc(e.notes||e.symptoms||'Без заметки')}</p></div><div class="entry-actions"><button onclick="editEntry('${e.id}')">Изменить</button><button onclick="deleteEntry('${e.id}')">Удалить</button></div></article>`).join(''):'<div class="card empty">Ничего не найдено.</div>'}
window.editEntry=id=>openEntry(entries.find(e=>e.id===id));window.deleteEntry=id=>{if(confirm('Удалить эту запись?')){entries=entries.filter(e=>e.id!==id);save();renderAll()}};$('#diarySearch').oninput=renderEntries;$('#painFilter').onchange=renderEntries;
const labels={operation:'Операция',mri:'МРТ',exam:'Приём / обследование',treatment:'Назначение'};let historyType='all';
function displayHistoryDate(d){if(/^\d{4}-\d{2}-\d{2}$/.test(d)){const [y,m,day]=d.split('-');return `${day}.${m}.${y}`}return d}
function historySort(d){if(/^\d{4}-\d{2}-\d{2}$/.test(d))return new Date(d);if(/^\d{2}\.\d{2}\.\d{4}$/.test(d)){const [a,m,y]=d.split('.');return new Date(`${y}-${m}-${a}`)}return new Date(`${String(d).slice(0,4)}-01-01`)}
function renderHistory(){const q=$('#historySearch').value.toLowerCase();const sorted=[...history].sort((a,b)=>historySort(b.date)-historySort(a.date));$('#timeline').innerHTML=sorted.filter(x=>(historyType==='all'||x.type===historyType)&&Object.values(x).join(' ').toLowerCase().includes(q)).map(x=>`<article class="timeline-item ${x.type}"><time class="timeline-date">${displayHistoryDate(x.date)}</time><span class="timeline-dot"></span><div class="timeline-content"><div class="timeline-actions"><button title="Изменить" onclick="editHistoryEvent('${x.id}')">✎</button><button title="Удалить" onclick="deleteHistoryEvent('${x.id}')">×</button></div><span class="type-label">${labels[x.type]}</span><h3>${esc(x.title)}</h3>${x.description?`<p>${esc(x.description)}</p>`:''}<div class="timeline-extra">${x.doctor?`<span class="badge">Врач: ${esc(x.doctor)}</span>`:''}${x.clinic?`<span class="badge">${esc(x.clinic)}</span>`:''}${x.medications?`<span class="badge">Лечение: ${esc(x.medications)}</span>`:''}</div>${x.notes?`<p class="muted">${esc(x.notes)}</p>`:''}</div></article>`).join('')||'<div class="empty">События не найдены.</div>'}
$('#historySearch').oninput=renderHistory;$$('.chip').forEach(b=>b.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');historyType=b.dataset.type;renderHistory()});
const historyDialog=$('#historyDialog'),historyForm=$('#historyForm');function toInputDate(d){if(/^\d{2}\.\d{2}\.\d{4}$/.test(d)){const [a,m,y]=d.split('.');return `${y}-${m}-${a}`}return /^\d{4}-\d{2}-\d{2}$/.test(d)?d:''}
function openHistoryEvent(item){historyForm.reset();historyForm.elements.id.value='';historyForm.elements.date.value=new Date().toISOString().slice(0,10);$('#historyDialogTitle').textContent=item?'Изменить событие':'Новое событие';if(item)Object.entries(item).forEach(([k,v])=>{if(historyForm.elements[k])historyForm.elements[k].value=k==='date'?toInputDate(v):v});historyDialog.showModal()}
$('#newHistoryEvent').onclick=()=>openHistoryEvent();$$('[data-history-close]').forEach(b=>b.onclick=()=>historyDialog.close());historyForm.onsubmit=e=>{e.preventDefault();const item=Object.fromEntries(new FormData(historyForm));item.id=item.id||newId();const i=history.findIndex(x=>x.id===item.id);i<0?history.push(item):history[i]=item;saveHistory();historyDialog.close();renderHistory()};window.editHistoryEvent=id=>openHistoryEvent(history.find(x=>x.id===id));window.deleteHistoryEvent=id=>{const item=history.find(x=>x.id===id);if(confirm(`Удалить событие «${item.title}»?`)){history=history.filter(x=>x.id!==id);saveHistory();renderHistory()}};
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const dataDialog=$('#dataDialog');$('#dataButton').onclick=()=>dataDialog.showModal();$('[data-data-close]').onclick=()=>dataDialog.close();$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),entries,history},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`health-diary-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};$('#importData').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.entries))throw Error();if(confirm(`Импортировать ${data.entries.length} записей дневника${Array.isArray(data.history)?` и ${data.history.length} событий истории`:''}? Текущие данные будут заменены.`)){entries=data.entries;if(Array.isArray(data.history)){history=normalizeHistory(data.history);saveHistory()}save();renderAll();dataDialog.close()}}catch{alert('Не удалось прочитать файл резервной копии.')}};
function renderProfile(){const box=$('#medicalCardContent');if(!box)return;if(!history.length){box.innerHTML='<article class="card"><p class="eyebrow">Приватные данные</p><h2>История пока не загружена</h2><p>Войдите в аккаунт и дождитесь завершения синхронизации.</p></article>';return}const count=type=>history.filter(x=>x.type===type).length;const recent=[...history].sort((a,b)=>historySort(b.date)-historySort(a.date)).slice(0,6);box.innerHTML=`<div class="profile-grid"><article class="card accent-card"><p class="eyebrow">Медицинская история</p><h2>${history.length} событий</h2><p>Приватная сводка загружена из защищённой базы.</p></article><article class="card"><p class="eyebrow">Основные события</p><h2>${count('operation')} операции · ${count('mri')} МРТ</h2><p>${count('exam')} приёмов и обследований · ${count('treatment')} назначений</p></article><article class="card" style="grid-column:1/-1"><p class="eyebrow">Последние события</p>${recent.map(x=>`<div class="mini-entry"><span>${esc(displayHistoryDate(x.date))}</span><div><strong>${esc(x.title)}</strong><br><small>${esc(x.description||labels[x.type]||'')}</small></div><span class="badge">${esc(labels[x.type]||'Событие')}</span></div>`).join('')}</article></div><article class="notice"><strong>Важно</strong><p>Эта сводка помогает хранить наблюдения, но не заменяет медицинскую консультацию.</p></article>`}
function groupedPain(list,key){const map={};list.forEach(e=>{const k=e[key]||'Не указано';(map[k]??=[]).push(+e.pain||0)});return Object.entries(map).map(([name,v])=>({name,avg:v.reduce((a,b)=>a+b,0)/v.length,count:v.length})).filter(x=>x.count>=2).sort((a,b)=>b.avg-a.avg)}
function statRows(items,max=10){return items.length?items.slice(0,6).map(x=>`<div class="stat-row"><span>${esc(x.name)}</span><div class="stat-track"><div class="stat-fill" style="width:${Math.min(100,x.avg/max*100)}%"></div></div><strong>${x.avg.toFixed(1)}</strong></div>`).join(''):'<p class="empty">Нужно минимум две записи для каждого фактора.</p>'}
function renderStats(){const box=$('#statsContent');if(!box)return;const p=$('#statsPeriod')?.value||'30',cut=p==='all'?0:Date.now()-(+p)*86400000,list=entries.filter(e=>!cut||new Date(e.date)>=cut);if(!list.length){box.innerHTML='<article class="card empty">За выбранный период записей пока нет.</article>';return}const pains=list.map(e=>+e.pain||0),avg=pains.reduce((a,b)=>a+b,0)/pains.length,max=Math.max(...pains),free=pains.filter(x=>x===0).length,withPain=pains.filter(x=>x>0);const bands=[{name:'Без боли',v:pains.filter(x=>x===0).length},{name:'Слабая 1–3',v:pains.filter(x=>x>=1&&x<=3).length},{name:'Средняя 4–6',v:pains.filter(x=>x>=4&&x<=6).length},{name:'Сильная 7–10',v:pains.filter(x=>x>=7).length}];const badSleep=list.filter(e=>+e.sleep>0&&+e.sleep<7),goodSleep=list.filter(e=>+e.sleep>=7),sleepAvg=a=>a.length?a.reduce((s,e)=>s+(+e.pain||0),0)/a.length:null;const insights=[];if(badSleep.length>=2&&goodSleep.length>=2)insights.push(`При сне менее 7 часов средняя боль ${sleepAvg(badSleep).toFixed(1)}, при 7+ часах — ${sleepAvg(goodSleep).toFixed(1)}.`);const topWeather=groupedPain(list,'weather')[0];if(topWeather)insights.push(`Наибольшая средняя боль среди погоды: ${topWeather.name} — ${topWeather.avg.toFixed(1)}.`);const topMood=groupedPain(list,'mood')[0];if(topMood)insights.push(`Наибольшая средняя боль среди настроений: ${topMood.name} — ${topMood.avg.toFixed(1)}.`);box.innerHTML=`<div class="stats-kpis"><article><small>Средняя боль</small><strong>${avg.toFixed(1)}</strong><small>из 10</small></article><article><small>Максимальная</small><strong>${max}</strong><small>из 10</small></article><article><small>Без боли</small><strong>${Math.round(free/list.length*100)}%</strong><small>${free} из ${list.length} записей</small></article><article><small>Записей с болью</small><strong>${withPain.length}</strong><small>за период</small></article></div><div class="stats-layout"><article class="card"><p class="eyebrow">Интенсивность</p><h2>Распределение записей</h2><div class="stat-list">${statRows(bands.map(x=>({name:x.name,avg:x.v})),Math.max(...bands.map(x=>x.v),1))}</div></article><article class="card"><p class="eyebrow">Наблюдения</p><h2>Возможные закономерности</h2><div class="insight-list">${insights.length?insights.map(x=>`<div class="insight">${esc(x)}</div>`).join(''):'<p class="empty">Добавляйте записи регулярно — здесь появятся наблюдения.</p>'}</div></article><article class="card"><p class="eyebrow">Погода</p><h2>Средняя боль</h2>${statRows(groupedPain(list,'weather'))}</article><article class="card"><p class="eyebrow">Настроение</p><h2>Средняя боль</h2>${statRows(groupedPain(list,'mood'))}</article></div><p class="stats-note">Статистика показывает совпадения в ваших записях, но не доказывает причину боли и не заменяет консультацию врача.</p>`}
$('#statsPeriod').onchange=renderStats;
function renderAll(){renderDashboard();renderEntries();renderHistory();renderProfile();renderStats()}renderAll();showView(location.hash.slice(1)||'today');
let installPrompt;const installButton=$('#installButton');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;installButton.hidden=false});installButton.onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;installButton.hidden=true};window.addEventListener('appinstalled',()=>{installPrompt=null;installButton.hidden=true});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
