const STORAGE_KEY='anastasiia-health-diary-v1',HISTORY_KEY='anastasiia-medical-history-v1',DOCTORS_KEY='anastasiia-doctors-v1';let medicalDocuments=[];
const defaultHistory=[];
function normalizeHistory(list){return list.map((x,i)=>Array.isArray(x)?{id:`pdf-${i}`,date:x[0],type:x[1],title:x[2],description:x[3]||'',doctor:'',clinic:'',medications:'',notes:''}:x)}
let history=normalizeHistory(JSON.parse(localStorage.getItem(HISTORY_KEY)||JSON.stringify(defaultHistory)));
let entries=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');
let doctors=JSON.parse(localStorage.getItem(DOCTORS_KEY)||'[]');
const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
const newId=()=>globalThis.crypto?.randomUUID?.()||`local-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const save=()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(entries));window.healthCloud?.scheduleSync()};
const saveHistory=()=>{localStorage.setItem(HISTORY_KEY,JSON.stringify(history));window.healthCloud?.scheduleSync()};
const saveDoctors=()=>{localStorage.setItem(DOCTORS_KEY,JSON.stringify(doctors));window.healthCloud?.scheduleSync()};
const fmt=d=>new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',year:'numeric'}).format(new Date(d));
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));location.hash=id;window.scrollTo(0,0);if(id==='diary')renderEntries();if(id==='statistics')renderStats();if(id==='history')renderHistory();if(id==='doctors')renderDoctors();}
$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-view-link]').forEach(b=>b.onclick=()=>showView(b.dataset.viewLink));
const dialog=$('#entryDialog'),form=$('#entryForm');
function openEntry(item){form.reset();form.elements.id.value='';form.elements.date.value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);if(item)Object.entries(item).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v});updatePain();dialog.showModal();}
$$('[data-new-entry]').forEach(b=>b.onclick=()=>openEntry());$$('[data-close]').forEach(b=>b.onclick=()=>dialog.close());
function updatePain(){const v=+form.elements.pain.value;$('#painOut').textContent=v+(v===0?' — нет боли':v<4?' — слабая':v<7?' — умеренная':' — сильная')};form.elements.pain.oninput=updatePain;
function saveEntry(){try{const item=Object.fromEntries(new FormData(form));item.date=item.date||new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);item.pain=Number(item.pain)||0;item.id=item.id||newId();const i=entries.findIndex(x=>x.id===item.id);i<0?entries.push(item):entries[i]=item;entries.sort((a,b)=>new Date(b.date)-new Date(a.date));save();dialog.close();renderAll();showView('diary')}catch(error){alert('Не удалось сохранить запись: '+error.message)}}
form.onsubmit=e=>{e.preventDefault();saveEntry()};
$$('.bp-input').forEach(input=>{input.addEventListener('input',()=>{const digits=input.value.replace(/\D/g,'').slice(0,6);input.value=digits.length>3?digits.slice(0,3)+'/'+digits.slice(3):digits})});
function renderDashboard(){const last=entries[0];$('#todayDate').textContent=new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long'}).format(new Date());$('#lastPain').textContent=last?`${last.pain}/10`:'Нет записей';$('#lastPainDate').textContent=last?fmt(last.date):'—';$('#lastBp').textContent=last?(last.bpLeft||last.bpRight||'Не измерено'):'—';$('#lastMood').textContent=last?(last.wellbeing||'—'):'—';$('#recentEntries').innerHTML=entries.length?entries.slice(0,3).map(entryMini).join(''):'<div class="empty">Записей пока нет</div>';renderChart();renderNextExam()}
function renderNextExam(){const box=$('#nextExamCard');if(!box)return;if(!history.length){box.innerHTML='<div class="card-head"><div><p class="eyebrow">Контроль</p><h2>Следующее обследование</h2></div></div><div class="date-tile"><strong>—</strong><span>История пока не загружена</span></div><p>Проверьте подключение к синхронизации.</p>';return}const today=new Date();today.setHours(0,0,0,0);const future=[...history].filter(x=>['mri','exam'].includes(x.type)&&historySort(x.date)>=today).sort((a,b)=>historySort(a.date)-historySort(b.date));const next=future[0];if(next){box.innerHTML=`<div class="card-head"><div><p class="eyebrow">Контроль</p><h2>Следующее обследование</h2></div></div><div class="date-tile"><strong>${esc(displayHistoryDate(next.date))}</strong><span>${esc(next.title)}</span></div><p>${esc(next.description||'Запланированное медицинское событие.')}</p>`}else box.innerHTML='<div class="card-head"><div><p class="eyebrow">Контроль</p><h2>Следующее обследование</h2></div></div><div class="date-tile"><strong>—</strong><span>Не запланировано</span></div><p>Добавьте следующее обследование в историю болезни.</p>'}
function entryMini(e){return `<div class="mini-entry"><span>${fmt(e.date)}</span><div><strong>${e.wellbeing}</strong> <span class="badge">Боль ${e.pain}/10</span><br><small>${esc(e.notes||e.symptoms||'Без заметки')}</small></div><span>${esc(e.bpLeft||e.bpRight||'—')}</span></div>`}
function renderChart(){const el=$('#painChart'),days=[...entries].slice(0,14).reverse();if(!days.length){el.className='chart empty-chart';el.textContent='Пока нет данных. Добавь первую запись.';return}el.className='chart';el.innerHTML=days.map(e=>`<div class="bar-wrap" title="${fmt(e.date)}: ${e.pain}/10"><div class="bar" style="height:${e.pain*10}%"></div><small>${new Date(e.date).getDate()}</small></div>`).join('')}
function renderEntries(){const q=$('#diarySearch').value.toLowerCase(),f=$('#painFilter').value;const list=entries.filter(e=>(!q||JSON.stringify(e).toLowerCase().includes(q))&&(f==='all'||f==='0'&&e.pain===0||f==='1'&&e.pain>0||f==='7'&&e.pain>=7));$('#entriesList').innerHTML=list.length?list.map(e=>`<article class="entry-card"><div><strong>${fmt(e.date)}</strong><br><small>${new Date(e.date).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</small></div><div><h3>${esc(e.wellbeing)} · боль ${e.pain}/10</h3><div class="entry-meta"><span class="badge">АД ${esc(e.bpLeft||'—')} / ${esc(e.bpRight||'—')}</span><span class="badge">${esc(e.weather)}</span><span class="badge">${esc(e.mood)}</span><span class="badge">сон ${esc(e.sleep||'—')} ч</span><span class="badge">цикл: ${esc(e.cycle)}</span></div><p>${esc(e.notes||e.symptoms||'Без заметки')}</p></div><div class="entry-actions"><button onclick="editEntry('${e.id}')">Изменить</button><button onclick="deleteEntry('${e.id}')">Удалить</button></div></article>`).join(''):'<div class="card empty">Ничего не найдено.</div>'}
window.editEntry=id=>openEntry(entries.find(e=>e.id===id));window.deleteEntry=id=>{if(confirm('Удалить эту запись?')){entries=entries.filter(e=>e.id!==id);save();renderAll()}};$('#diarySearch').oninput=renderEntries;$('#painFilter').onchange=renderEntries;
const labels={operation:'Операция',mri:'МРТ',exam:'Приём / обследование',treatment:'Назначение'};let historyType='all';
function displayHistoryDate(d){if(/^\d{4}-\d{2}-\d{2}$/.test(d)){const [y,m,day]=d.split('-');return `${day}.${m}.${y}`}return d}
function historySort(d){if(/^\d{4}-\d{2}-\d{2}$/.test(d))return new Date(d);if(/^\d{2}\.\d{2}\.\d{4}$/.test(d)){const [a,m,y]=d.split('.');return new Date(`${y}-${m}-${a}`)}return new Date(`${String(d).slice(0,4)}-01-01`)}
function renderHistory(){const q=$('#historySearch').value.toLowerCase();const sorted=[...history].sort((a,b)=>historySort(b.date)-historySort(a.date));$('#timeline').innerHTML=sorted.filter(x=>(historyType==='all'||x.type===historyType)&&Object.values(x).join(' ').toLowerCase().includes(q)).map(x=>{const docs=medicalDocuments.filter(d=>d.history_event_id===x.id);return`<article class="timeline-item ${x.type}"><time class="timeline-date">${displayHistoryDate(x.date)}</time><span class="timeline-dot"></span><div class="timeline-content"><div class="timeline-actions"><button title="Изменить" onclick="editHistoryEvent('${x.id}')">✎</button><button title="Удалить" onclick="deleteHistoryEvent('${x.id}')">×</button></div><span class="type-label">${labels[x.type]}</span><h3>${esc(x.title)}</h3>${x.description?`<p>${esc(x.description)}</p>`:''}<div class="timeline-extra">${x.doctor?`<span class="badge">Врач: ${esc(x.doctor)}</span>`:''}${x.clinic?`<span class="badge">${esc(x.clinic)}</span>`:''}${x.medications?`<span class="badge">Лечение: ${esc(x.medications)}</span>`:''}</div>${x.notes?`<p class="muted">${esc(x.notes)}</p>`:''}${docs.length?`<div class="event-attachments"><strong>Вложения (${docs.length})</strong>${docs.map(d=>`<button type="button" onclick="openMedicalDocument('${d.id}')">${d.mime_type?.startsWith('image/')?'Изображение':'PDF'} · ${esc(d.title)}</button>`).join('')}</div>`:''}</div></article>`}).join('')||'<div class="empty">События не найдены.</div>'}
$('#historySearch').oninput=renderHistory;$$('.chip').forEach(b=>b.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');historyType=b.dataset.type;renderHistory()});
const historyDialog=$('#historyDialog'),historyForm=$('#historyForm'),historyAttachmentList=$('#historyAttachmentList'),historyAttachmentMessage=$('#historyAttachmentMessage');function toInputDate(d){if(/^\d{2}\.\d{2}\.\d{4}$/.test(d)){const [a,m,y]=d.split('.');return `${y}-${m}-${a}`}return /^\d{4}-\d{2}-\d{2}$/.test(d)?d:''}
function renderHistoryDialogAttachments(eventId){const docs=medicalDocuments.filter(d=>d.history_event_id===eventId);historyAttachmentList.innerHTML=docs.map(d=>`<div><button type="button" class="text-button" onclick="openMedicalDocument('${d.id}')">${d.mime_type?.startsWith('image/')?'🖼':'PDF'} ${esc(d.title)}</button><button type="button" class="attachment-delete" onclick="deleteHistoryAttachment('${d.id}','${eventId}')" aria-label="Удалить">×</button></div>`).join('')||'<span class="muted">Прикреплённых файлов пока нет.</span>'}
function openHistoryEvent(item){historyForm.reset();historyAttachmentMessage.textContent='';historyForm.elements.id.value='';historyForm.elements.date.value=new Date().toISOString().slice(0,10);$('#historyDialogTitle').textContent=item?'Изменить событие':'Новое событие';if(item)Object.entries(item).forEach(([k,v])=>{if(historyForm.elements[k])historyForm.elements[k].value=k==='date'?toInputDate(v):v});renderHistoryDialogAttachments(item?.id||'');historyDialog.showModal()}
$('#newHistoryEvent').onclick=()=>openHistoryEvent();$$('[data-history-close]').forEach(b=>b.onclick=()=>historyDialog.close());historyForm.onsubmit=async e=>{e.preventDefault();const fd=new FormData(historyForm),files=[...historyForm.elements.attachments.files],item=Object.fromEntries(fd);delete item.attachments;item.id=item.id||newId();if(files.length&&!window.healthCloud?.isSignedIn()){historyAttachmentMessage.textContent='Чтобы прикрепить файлы, сначала войдите в аккаунт.';return}for(const file of files){if(!['application/pdf','image/jpeg','image/png','image/webp'].includes(file.type)){historyAttachmentMessage.textContent=`Файл «${file.name}» имеет неподдерживаемый формат.`;return}if(file.size>15*1024*1024){historyAttachmentMessage.textContent=`Файл «${file.name}» больше 15 МБ.`;return}}const i=history.findIndex(x=>x.id===item.id);i<0?history.push(item):history[i]=item;saveHistory();if(files.length){historyAttachmentMessage.textContent='Загрузка вложений…';for(const file of files){const result=await window.healthCloud.uploadDocument({file,title:file.name.replace(/\.[^.]+$/,''),category:'visit',documentDate:item.date,historyEventId:item.id});if(result?.error){historyAttachmentMessage.textContent=result.error;await loadDocuments();renderHistory();return}}await loadDocuments()}historyDialog.close();renderHistory()};window.editHistoryEvent=id=>openHistoryEvent(history.find(x=>x.id===id));window.deleteHistoryEvent=id=>{const item=history.find(x=>x.id===id);if(confirm(`Удалить событие «${item.title}»? Вложения останутся в приватном архиве.`)){history=history.filter(x=>x.id!==id);saveHistory();renderHistory()}};
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const dataDialog=$('#dataDialog');$('#dataButton').onclick=()=>dataDialog.showModal();$('[data-data-close]').onclick=()=>dataDialog.close();$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),entries,history},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`health-diary-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};$('#importData').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(data.historyOnly&&Array.isArray(data.history)){if(confirm(`Обновить ${data.history.length} событий медицинской истории? Записи дневника останутся без изменений.`)){history=normalizeHistory(data.history);saveHistory();renderAll();dataDialog.close()}return}if(!Array.isArray(data.entries))throw Error();if(confirm(`Импортировать ${data.entries.length} записей дневника${Array.isArray(data.history)?` и ${data.history.length} событий истории`:''}? Текущие данные будут заменены.`)){entries=data.entries;if(Array.isArray(data.history)){history=normalizeHistory(data.history);saveHistory()}save();renderAll();dataDialog.close()}}catch{alert('Не удалось прочитать файл резервной копии.')}};
function renderProfile(){const box=$('#medicalCardContent');if(!box)return;if(!history.length){box.innerHTML='<article class="card"><p class="eyebrow">Приватные данные</p><h2>История пока не загружена</h2><p>Войдите в аккаунт и дождитесь завершения синхронизации.</p></article>';return}const count=type=>history.filter(x=>x.type===type).length;const recent=[...history].sort((a,b)=>historySort(b.date)-historySort(a.date)).slice(0,6);box.innerHTML=`<div class="profile-grid"><article class="card accent-card"><p class="eyebrow">Медицинская история</p><h2>${history.length} событий</h2><p>Приватная сводка загружена из защищённой базы.</p></article><article class="card"><p class="eyebrow">Основные события</p><h2>${count('operation')} операции · ${count('mri')} МРТ</h2><p>${count('exam')} приёмов и обследований · ${count('treatment')} назначений</p></article><article class="card" style="grid-column:1/-1"><p class="eyebrow">Последние события</p>${recent.map(x=>`<div class="mini-entry"><span>${esc(displayHistoryDate(x.date))}</span><div><strong>${esc(x.title)}</strong><br><small>${esc(x.description||labels[x.type]||'')}</small></div><span class="badge">${esc(labels[x.type]||'Событие')}</span></div>`).join('')}</article></div><article class="notice"><strong>Важно</strong><p>Эта сводка помогает хранить наблюдения, но не заменяет медицинскую консультацию.</p></article>`}
function groupedPain(list,key){const map={};list.forEach(e=>{const k=e[key]||'Не указано';(map[k]??=[]).push(+e.pain||0)});return Object.entries(map).map(([name,v])=>({name,avg:v.reduce((a,b)=>a+b,0)/v.length,count:v.length})).filter(x=>x.count>=2).sort((a,b)=>b.avg-a.avg)}
function statRows(items,max=10){return items.length?items.slice(0,6).map(x=>`<div class="stat-row"><span>${esc(x.name)}</span><div class="stat-track"><div class="stat-fill" style="width:${Math.min(100,x.avg/max*100)}%"></div></div><strong>${x.avg.toFixed(1)}</strong></div>`).join(''):'<p class="empty">Нужно минимум две записи для каждого фактора.</p>'}
function renderStats(){const box=$('#statsContent');if(!box)return;const p=$('#statsPeriod')?.value||'30',cut=p==='all'?0:Date.now()-(+p)*86400000,list=entries.filter(e=>!cut||new Date(e.date)>=cut);if(!list.length){box.innerHTML='<article class="card empty">За выбранный период записей пока нет.</article>';return}const pains=list.map(e=>+e.pain||0),avg=pains.reduce((a,b)=>a+b,0)/pains.length,max=Math.max(...pains),free=pains.filter(x=>x===0).length,withPain=pains.filter(x=>x>0);const bands=[{name:'Без боли',v:pains.filter(x=>x===0).length},{name:'Слабая 1–3',v:pains.filter(x=>x>=1&&x<=3).length},{name:'Средняя 4–6',v:pains.filter(x=>x>=4&&x<=6).length},{name:'Сильная 7–10',v:pains.filter(x=>x>=7).length}];const badSleep=list.filter(e=>+e.sleep>0&&+e.sleep<7),goodSleep=list.filter(e=>+e.sleep>=7),sleepAvg=a=>a.length?a.reduce((s,e)=>s+(+e.pain||0),0)/a.length:null;const insights=[];if(badSleep.length>=2&&goodSleep.length>=2)insights.push(`При сне менее 7 часов средняя боль ${sleepAvg(badSleep).toFixed(1)}, при 7+ часах — ${sleepAvg(goodSleep).toFixed(1)}.`);const topWeather=groupedPain(list,'weather')[0];if(topWeather)insights.push(`Наибольшая средняя боль среди погоды: ${topWeather.name} — ${topWeather.avg.toFixed(1)}.`);const topMood=groupedPain(list,'mood')[0];if(topMood)insights.push(`Наибольшая средняя боль среди настроений: ${topMood.name} — ${topMood.avg.toFixed(1)}.`);box.innerHTML=`<div class="stats-kpis"><article><small>Средняя боль</small><strong>${avg.toFixed(1)}</strong><small>из 10</small></article><article><small>Максимальная</small><strong>${max}</strong><small>из 10</small></article><article><small>Без боли</small><strong>${Math.round(free/list.length*100)}%</strong><small>${free} из ${list.length} записей</small></article><article><small>Записей с болью</small><strong>${withPain.length}</strong><small>за период</small></article></div><div class="stats-layout"><article class="card"><p class="eyebrow">Интенсивность</p><h2>Распределение записей</h2><div class="stat-list">${statRows(bands.map(x=>({name:x.name,avg:x.v})),Math.max(...bands.map(x=>x.v),1))}</div></article><article class="card"><p class="eyebrow">Наблюдения</p><h2>Возможные закономерности</h2><div class="insight-list">${insights.length?insights.map(x=>`<div class="insight">${esc(x)}</div>`).join(''):'<p class="empty">Добавляйте записи регулярно — здесь появятся наблюдения.</p>'}</div></article><article class="card"><p class="eyebrow">Погода</p><h2>Средняя боль</h2>${statRows(groupedPain(list,'weather'))}</article><article class="card"><p class="eyebrow">Настроение</p><h2>Средняя боль</h2>${statRows(groupedPain(list,'mood'))}</article></div><p class="stats-note">Статистика показывает совпадения в ваших записях, но не доказывает причину боли и не заменяет консультацию врача.</p>`}
$('#statsPeriod').onchange=renderStats;
const doctorDialog=$('#doctorDialog'),doctorForm=$('#doctorForm');
const pdfDoctors=[
{id:'pdf-doctor-stusik',name:'Стусик',specialty:'Вирусолог',clinic:'',phone:'',email:'',address:'',website:'',notes:'[Из истории болезни]\n08.07.2021: назначены Вальтрекс 500 мг 4 раза в день на 2 недели, Укрлив 500 мг на ночь на 1-2 месяца, L-лизин 500 мг 2 раза в день на 1 месяц.\n31.07.2021: продолжение лечения - Вальтрекс 500 мг 2 раза в день 2 недели, Укрлив 500 мг на ночь, L-лизин 500 мг 2 раза в день.\n16.08.2021: после выявления герпеса 7 типа - Вальтрекс по 2 таблетки 500 мг 2 раза в день 2 недели; продолжить Укрлив и L-лизин.'},
{id:'pdf-doctor-piantkovska',name:'Пянтковская',specialty:'Невролог',clinic:'',phone:'',email:'',address:'',website:'',notes:'[Из истории болезни]\n28.07.2021: назначен 5-MTHF 1 мг, 1 капсула 1 раз в день, курс 1 месяц.\n01.08.2021: по результатам ЭЭГ и УЗИ назначены Лирика (в записи указано: по половине таблетки 2 раза в день; препарат не принимался) и массаж шейно-воротниковой зоны, который также не проводился из-за кисты.'},
{id:'pdf-doctor-plavskyi',name:'Плавский',specialty:'Нейрохирург / хирург',clinic:'НДСЛ «Охматдит»',phone:'',email:'',address:'Киев, Украина',website:'',notes:'[Из истории болезни]\nПроводил наблюдение после первой эндоскопической операции 07.06.2021.\n30.08.2021: просмотрел контрольное МРТ, состояние стабильное; разрешил обычный образ жизни, рекомендовал повторное МРТ через 6 месяцев.\n11.02.2022: после МРТ сообщил о необходимости фенестрации кисты ориентировочно в марте-апреле 2022 года.'},
{id:'pdf-doctor-tkachenko',name:'Ткаченко Тина Владимировна',specialty:'Невропатолог',clinic:'Медицинский центр ADONIS',phone:'',email:'',address:'Киев, ул. Жилянская, 72',website:'',notes:'[Из истории болезни]\n11.09.2021: консультация из-за эмоциональных всплесков, перепадов настроения и плаксивости. Назначены Нервохель 1 таблетка 3 раза в день, Ноофен 250 мг 1 таблетка 2 раза в день, Глицисед 1 таблетка 3 раза в день.\n15.09.2021: телефонная консультация - продолжить лечение.\nРекомендации для поездки: при внутричерепном давлении Диакарб и Аспаркам не более 3 дней; Лимфомиазот; Вертигохеель перед перелётом; Бруфен при головной боли; при повышении артериального давления - спазмолитик, покой и контроль давления.'},
{id:'pdf-doctor-schreiber',name:'Dr. med. Lutz Schreiber',specialty:'Детский нейрохирург, главный врач',clinic:'Klinik für Pädiatrische Neurochirurgie, Knappschaft Kliniken Gelsenkirchen',phone:'0209 369-601; амбулатория 0209 369-602',email:'lutz.schreiber@knappschaft-kliniken.de',address:'Schernerweg 4, 45894 Gelsenkirchen, Deutschland',website:'https://www.knappschaft-kliniken.de/gelsenkirchen/kinder-und-jugendklinik/kliniken/klinik-fuer-paediatrische-neurochirurgie/',notes:'[Из истории болезни]\n05.04.2022: подтвердил прогрессирование кисты и необходимость фенестрации.\n04.05.2022, Klinikum Vest Recklinghausen: выполнил вторую операцию - фенестрацию кисты в трёх местах.\n29.06.2023, Kinder- und Jugendklinik Gelsenkirchen: выполнил третью операцию - повторную фенестрацию и установку катетера для отведения жидкости из кисты.\nКонтрольные МРТ: после операций и планово в Datteln. 21.10.2025 сообщил, что передняя часть кисты уменьшилась ещё на 3 мм; динамика очень хорошая, следующее МРТ требуется через 2 года.\nСекретариат: kinderneurochirurgie.gelsenkirchen@knappschaft-gelsenkirchen.de, тел. 0209 369-601, факс 0209 369-610.'},
{id:'pdf-doctor-androcenter',name:'Невропатолог Андроцентра (имя не указано)',specialty:'Невропатолог',clinic:'Андроцентр',phone:'',email:'',address:'Обухов, Украина',website:'',notes:'[Из истории болезни]\n27.08.2021: консультация. Рекомендовано прекратить избыточный приём противовирусных препаратов и сдать развёрнутый общий анализ крови, IgG и IgM к герпесу 1, 2 и 7 типов, а также печёночные пробы.'}
];
function doctorKey(value){return String(value||'').toLowerCase().replace(/dr\.?|med\.?|док\.?/g,'').replace(/[^a-zа-яёіїєґ]+/g,' ').trim()}
function mergePdfDoctors(){let changed=false;for(const source of pdfDoctors){const sourceKey=doctorKey(source.name),sourceTokens=sourceKey.split(' ').filter(t=>t.length>=5&&!['врач','указано','невропатолог','нейрохирург'].includes(t)),existing=doctors.find(d=>{const key=doctorKey(d.name),tokens=key.split(' ');return key===sourceKey||sourceTokens.some(token=>tokens.includes(token))});if(!existing){doctors.push({...source});changed=true;continue}for(const field of ['specialty','clinic','phone','email','address','website'])if(!existing[field]&&source[field]){existing[field]=source[field];changed=true}if(!String(existing.notes||'').includes('[Из истории болезни]')){existing.notes=[existing.notes,source.notes].filter(Boolean).join('\n\n');changed=true}}return changed}
if(mergePdfDoctors())localStorage.setItem(DOCTORS_KEY,JSON.stringify(doctors));
function doctorHref(kind,value){if(!value)return'';if(kind==='phone')return`tel:${value.replace(/[^+\d]/g,'')}`;if(kind==='email')return`mailto:${value}`;return /^https?:\/\//i.test(value)?value:`https://${value}`}
function renderDoctors(){const box=$('#doctorsList');if(!box)return;const q=($('#doctorSearch')?.value||'').trim().toLowerCase(),list=[...doctors].sort((a,b)=>(a.name||'').localeCompare(b.name||'','ru')).filter(d=>Object.values(d).join(' ').toLowerCase().includes(q));box.innerHTML=list.length?list.map(d=>`<article class="doctor-card"><div class="doctor-avatar">${esc((d.name||'?').trim().charAt(0).toUpperCase())}</div><div class="doctor-main"><p class="eyebrow">${esc(d.specialty||'Врач')}</p><h2>${esc(d.name)}</h2>${d.clinic?`<p><strong>${esc(d.clinic)}</strong></p>`:''}${d.address?`<p class="muted">${esc(d.address)}</p>`:''}<div class="doctor-links">${d.phone?`<a href="${esc(doctorHref('phone',d.phone))}">Позвонить · ${esc(d.phone)}</a>`:''}${d.email?`<a href="${esc(doctorHref('email',d.email))}">Email · ${esc(d.email)}</a>`:''}${d.website?`<a href="${esc(doctorHref('website',d.website))}" target="_blank" rel="noopener">Открыть сайт</a>`:''}</div>${d.notes?`<div class="doctor-notes"><strong>Важная информация</strong><p>${esc(d.notes)}</p></div>`:''}</div><div class="doctor-actions"><button onclick="editDoctor('${d.id}')" title="Изменить">✎</button><button onclick="deleteDoctor('${d.id}')" title="Удалить">×</button></div></article>`).join(''):'<article class="card empty">Врачей пока нет. Добавьте первый контакт.</article>'}
function openDoctor(item){doctorForm.reset();doctorForm.elements.id.value='';$('#doctorDialogTitle').textContent=item?'Изменить контакт':'Новый врач';if(item)Object.entries(item).forEach(([k,v])=>{if(doctorForm.elements[k])doctorForm.elements[k].value=v||''});doctorDialog.showModal()}
$('#newDoctorButton').onclick=()=>openDoctor();$('#doctorSearch').oninput=renderDoctors;$$('[data-doctor-close]').forEach(b=>b.onclick=()=>doctorDialog.close());doctorForm.onsubmit=e=>{e.preventDefault();const item=Object.fromEntries(new FormData(doctorForm));item.id=item.id||newId();const i=doctors.findIndex(d=>d.id===item.id);i<0?doctors.push(item):doctors[i]=item;saveDoctors();doctorDialog.close();renderDoctors()};window.editDoctor=id=>openDoctor(doctors.find(d=>d.id===id));window.deleteDoctor=id=>{const item=doctors.find(d=>d.id===id);if(item&&confirm(`Удалить врача «${item.name}»?`)){doctors=doctors.filter(d=>d.id!==id);saveDoctors();renderDoctors()}};
window.addEventListener('health-auth-changed',event=>{if(event.detail?.signedIn&&mergePdfDoctors()){localStorage.setItem(DOCTORS_KEY,JSON.stringify(doctors));renderDoctors();saveDoctors()}});
function renderAll(){renderDashboard();renderEntries();renderHistory();renderProfile();renderStats();renderDoctors()}renderAll();showView(location.hash.slice(1)||'today');

/* Private PDF archive */
const documentLabels={hospital:'Выписка из больницы',mri:'МРТ / обследование',operation:'Операция',doctor:'Заключение врача',analysis:'Анализы',visit:'Вложение к приёму',other:'Другое'};
const documentDialog=$('#documentDialog'),documentForm=$('#documentForm'),documentMessage=$('#documentMessage');
$('#uploadDocumentButton').onclick=()=>{documentForm.reset();documentForm.elements.document_date.value=new Date().toISOString().slice(0,10);documentMessage.textContent='';documentDialog.showModal()};
$$('[data-document-close]').forEach(x=>x.onclick=()=>documentDialog.close());
documentForm.onsubmit=async e=>{e.preventDefault();const file=documentForm.elements.file.files[0];if(!window.healthCloud?.isSignedIn()){documentMessage.textContent='Сначала войдите в аккаунт.';return}if(!file||file.type!=='application/pdf'){documentMessage.textContent='Выберите PDF-файл.';return}if(file.size>15*1024*1024){documentMessage.textContent='Файл больше 15 МБ.';return}documentMessage.textContent='Загрузка…';const result=await window.healthCloud.uploadDocument({file,title:documentForm.elements.title.value.trim(),category:documentForm.elements.category.value,documentDate:documentForm.elements.document_date.value});if(result?.error){documentMessage.textContent=result.error;return}documentDialog.close();await loadDocuments()};
async function loadDocuments(){const box=$('#documentsList');if(!window.healthCloud?.isSignedIn()){medicalDocuments=[];box.innerHTML='<article class="card empty">Войдите, чтобы загрузить документы.</article>';renderHistory();return}box.innerHTML='<article class="card empty">Загрузка документов…</article>';const result=await window.healthCloud.listDocuments();if(result?.error){box.innerHTML=`<article class="card empty">${esc(result.error)}</article>`;return}medicalDocuments=result.data||[];renderDocuments();renderHistory()}
function renderDocuments(){const box=$('#documentsList');box.innerHTML=medicalDocuments.length?medicalDocuments.map(d=>`<article class="document-card"><div class="document-icon">${d.mime_type?.startsWith('image/')?'IMG':'PDF'}</div><div><strong>${esc(d.title)}</strong><div class="muted">${esc(documentLabels[d.category]||documentLabels.other)} · ${esc(displayHistoryDate(d.document_date))}</div></div><div class="document-actions"><button onclick="openMedicalDocument('${d.id}')">Открыть</button><button onclick="deleteMedicalDocument('${d.id}')">Удалить</button></div></article>`).join(''):'<article class="card empty">Документов пока нет. Добавьте первую выписку в PDF.</article>'}
window.openMedicalDocument=async id=>{const result=await window.healthCloud?.openDocument(id);if(result?.error)alert(result.error);else if(result?.url)window.open(result.url,'_blank','noopener')};
window.deleteMedicalDocument=async id=>{const item=medicalDocuments.find(x=>x.id===id);if(!item||!confirm(`Удалить документ «${item.title}»?`))return;const result=await window.healthCloud?.deleteDocument(id);if(result?.error)alert(result.error);else await loadDocuments()};
window.deleteHistoryAttachment=async(id,eventId)=>{const item=medicalDocuments.find(x=>x.id===id);if(!item||!confirm(`Удалить вложение «${item.title}»?`))return;const result=await window.healthCloud?.deleteDocument(id);if(result?.error)alert(result.error);else{await loadDocuments();renderHistoryDialogAttachments(eventId)}};
window.addEventListener('health-auth-changed',loadDocuments);

/* Structured multilingual doctor report. Free-text notes stay in their original language. */
const reportText={
ru:{title:'Медицинская выписка для консультации',created:'Подготовлено',notice:'Документ составлен по записям пациента и не является официальным медицинским заключением.',history:'Медицинская история',diary:'Самочувствие и дневник',documents:'Доступные медицинские документы',date:'Дата',event:'Событие',doctor:'Врач / клиника',result:'Результат и лечение',pain:'Боль',wellbeing:'Самочувствие',pressure:'Давление',notes:'Заметки',original:'Свободный текст приведён на языке оригинала.',print:'Печать / сохранить PDF',close:'Закрыть',none:'Нет данных'},
uk:{title:'Медична виписка для консультації',created:'Підготовлено',notice:'Документ складено за записами пацієнта і не є офіційним медичним висновком.',history:'Медична історія',diary:'Самопочуття та щоденник',documents:'Доступні медичні документи',date:'Дата',event:'Подія',doctor:'Лікар / клініка',result:'Результат і лікування',pain:'Біль',wellbeing:'Самопочуття',pressure:'Тиск',notes:'Нотатки',original:'Вільний текст наведено мовою оригіналу.',print:'Друк / зберегти PDF',close:'Закрити',none:'Немає даних'},
en:{title:'Medical summary for consultation',created:'Prepared',notice:'This document is based on the patient’s own records and is not an official medical report.',history:'Medical history',diary:'Symptoms and health diary',documents:'Available medical documents',date:'Date',event:'Event',doctor:'Doctor / clinic',result:'Result and treatment',pain:'Pain',wellbeing:'Well-being',pressure:'Blood pressure',notes:'Notes',original:'Free-text entries are shown in their original language.',print:'Print / save as PDF',close:'Close',none:'No data'},
de:{title:'Medizinische Zusammenfassung für die Konsultation',created:'Erstellt',notice:'Dieses Dokument basiert auf den eigenen Aufzeichnungen der Patientin und ist kein offizieller Arztbericht.',history:'Krankengeschichte',diary:'Befinden und Gesundheitstagebuch',documents:'Verfügbare medizinische Dokumente',date:'Datum',event:'Ereignis',doctor:'Arzt / Klinik',result:'Ergebnis und Behandlung',pain:'Schmerz',wellbeing:'Befinden',pressure:'Blutdruck',notes:'Notizen',original:'Freitexte werden in der Originalsprache angezeigt.',print:'Drucken / als PDF speichern',close:'Schließen',none:'Keine Daten'},
pl:{title:'Podsumowanie medyczne na konsultację',created:'Przygotowano',notice:'Dokument powstał na podstawie własnych zapisów pacjentki i nie jest oficjalną dokumentacją medyczną.',history:'Historia medyczna',diary:'Samopoczucie i dziennik zdrowia',documents:'Dostępne dokumenty medyczne',date:'Data',event:'Zdarzenie',doctor:'Lekarz / placówka',result:'Wynik i leczenie',pain:'Ból',wellbeing:'Samopoczucie',pressure:'Ciśnienie',notes:'Notatki',original:'Tekst swobodny pozostaje w języku oryginalnym.',print:'Drukuj / zapisz PDF',close:'Zamknij',none:'Brak danych'}};
const reportDialog=$('#doctorReportDialog'),reportForm=$('#doctorReportForm'),reportBox=$('#doctorReportPrint');
$('#doctorReportButton').onclick=()=>reportDialog.showModal();$$('[data-report-close]').forEach(x=>x.onclick=()=>reportDialog.close());
reportForm.onsubmit=e=>{e.preventDefault();const fd=new FormData(reportForm),t=reportText[fd.get('language')]||reportText.ru,period=fd.get('period'),cut=period==='all'?0:Date.now()-(+period)*86400000,diary=entries.filter(x=>!cut||new Date(x.date)>=cut).sort((a,b)=>new Date(b.date)-new Date(a.date)),hist=[...history].sort((a,b)=>historySort(b.date)-historySort(a.date));const historyHtml=fd.get('includeHistory')?`<section><h2>${t.history}</h2>${hist.length?hist.map(x=>`<article class="report-item"><div class="report-date">${esc(displayHistoryDate(x.date))}</div><div><strong>${esc(x.title)}</strong><p>${esc([x.doctor,x.clinic].filter(Boolean).join(' · ')||'')}</p><p>${esc([x.description,x.medications].filter(Boolean).join(' — ')||'')}</p></div></article>`).join(''):`<p>${t.none}</p>`}</section>`:'';const diaryHtml=fd.get('includeNotes')?`<section><h2>${t.diary}</h2>${diary.length?diary.map(x=>`<article class="report-item"><div class="report-date">${esc(fmt(x.date))}</div><div><strong>${t.pain}: ${Number(x.pain)||0}/10 · ${t.wellbeing}: ${esc(x.wellbeing||'—')}</strong><p>${t.pressure}: ${esc(x.bpLeft||x.bpRight||'—')}</p><p>${t.notes}: ${esc(x.notes||x.symptoms||'—')}</p></div></article>`).join(''):`<p>${t.none}</p>`}</section>`:'';const docsHtml=fd.get('includeDocuments')?`<section><h2>${t.documents}</h2>${medicalDocuments.length?`<ul>${medicalDocuments.map(x=>`<li>${esc(displayHistoryDate(x.document_date))} — ${esc(x.title)}</li>`).join('')}</ul>`:`<p>${t.none}</p>`}</section>`:'';reportBox.innerHTML=`<div class="report-sheet"><div class="report-screen-actions"><button onclick="closeDoctorReport()">${t.close}</button><button onclick="printDoctorReport()">${t.print}</button></div><header><p>${t.created}: ${new Date().toLocaleDateString(fd.get('language'))}</p><h1>${t.title}</h1><div class="report-notice">${t.notice}</div></header>${historyHtml}${diaryHtml}${docsHtml}<p class="report-original">${t.original}</p></div>`;reportDialog.close();document.body.classList.add('show-doctor-report');window.scrollTo(0,0)};
window.closeDoctorReport=()=>document.body.classList.remove('show-doctor-report');window.printDoctorReport=()=>{document.body.classList.add('printing-doctor-report');window.print()};window.addEventListener('afterprint',()=>document.body.classList.remove('printing-doctor-report'));
let installPrompt;const installButton=$('#installButton');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;installButton.hidden=false});installButton.onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;installButton.hidden=true};window.addEventListener('appinstalled',()=>{installPrompt=null;installButton.hidden=true});if('serviceWorker'in navigator){let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloading)return;reloading=true;location.reload()});window.addEventListener('load',async()=>{try{const registration=await navigator.serviceWorker.register('./service-worker.js',{updateViaCache:'none'});await registration.update()}catch{}})}
